"""
Database layer using SQLAlchemy + SQLite.
Stores raw EUA price records and derived analytics snapshots.
"""

import logging
from datetime import date, datetime
from pathlib import Path
from typing import Optional

import pandas as pd
from sqlalchemy import (
    Column, Date, DateTime, Float, Integer, String, Text,
    create_engine, text
)
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

logger = logging.getLogger(__name__)

DB_PATH = Path(__file__).parent.parent / "data" / "carbon_tracker.db"
DB_URL = f"sqlite:///{DB_PATH}"


class Base(DeclarativeBase):
    pass


class EUAPrice(Base):
    """Daily EUA carbon price record."""
    __tablename__ = "eua_prices"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(Date, nullable=False, unique=True, index=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    close = Column(Float, nullable=False)
    volume = Column(Integer)
    source = Column(String(100))
    ingested_at = Column(DateTime, default=datetime.utcnow)


class Alert(Base):
    """Price movement alerts generated by the pipeline."""
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    alert_date = Column(Date, nullable=False, index=True)
    alert_type = Column(String(50))   # e.g. "PRICE_DROP", "PRICE_SPIKE"
    message = Column(Text)
    price = Column(Float)
    change_pct = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)


def get_engine():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    return create_engine(DB_URL, connect_args={"check_same_thread": False})


def init_db():
    """Create all tables if they don't exist."""
    engine = get_engine()
    Base.metadata.create_all(engine)
    logger.info(f"Database ready at {DB_PATH}")
    return engine


def get_session() -> Session:
    engine = get_engine()
    SessionLocal = sessionmaker(bind=engine)
    return SessionLocal()


def upsert_prices(df: pd.DataFrame) -> int:
    """
    Insert new price records, skipping dates already in DB.
    Returns the number of new rows inserted.
    """
    session = get_session()
    inserted = 0
    try:
        for _, row in df.iterrows():
            exists = session.query(EUAPrice).filter(EUAPrice.date == row["date"]).first()
            if not exists:
                record = EUAPrice(
                    date=row["date"],
                    open=row.get("open"),
                    high=row.get("high"),
                    low=row.get("low"),
                    close=row["close"],
                    volume=row.get("volume"),
                    source=row.get("source"),
                )
                session.add(record)
                inserted += 1
        session.commit()
        logger.info(f"Inserted {inserted} new price records.")
    except Exception as e:
        session.rollback()
        logger.error(f"DB insert failed: {e}")
        raise
    finally:
        session.close()
    return inserted


def get_prices_df(days: Optional[int] = None) -> pd.DataFrame:
    """Retrieve price history as a DataFrame, optionally limited to last N days."""
    session = get_session()
    try:
        query = session.query(EUAPrice).order_by(EUAPrice.date)
        records = query.all()
        if not records:
            return pd.DataFrame()
        df = pd.DataFrame([{
            "date": r.date,
            "open": r.open,
            "high": r.high,
            "low": r.low,
            "close": r.close,
            "volume": r.volume,
            "source": r.source,
        } for r in records])
        if days:
            df = df.tail(days)
        return df
    finally:
        session.close()


def save_alert(alert_date: date, alert_type: str, message: str, price: float, change_pct: float):
    """Persist a price alert to the DB."""
    session = get_session()
    try:
        alert = Alert(
            alert_date=alert_date,
            alert_type=alert_type,
            message=message,
            price=price,
            change_pct=change_pct,
        )
        session.add(alert)
        session.commit()
    except Exception as e:
        session.rollback()
        logger.error(f"Failed to save alert: {e}")
    finally:
        session.close()


def get_alerts_df(days: int = 30) -> pd.DataFrame:
    """Retrieve recent alerts as a DataFrame."""
    session = get_session()
    try:
        records = session.query(Alert).order_by(Alert.alert_date.desc()).limit(days).all()
        if not records:
            return pd.DataFrame()
        return pd.DataFrame([{
            "date": r.alert_date,
            "type": r.alert_type,
            "message": r.message,
            "price": r.price,
            "change_pct": r.change_pct,
        } for r in records])
    finally:
        session.close()
def delete_synthetic_records():
    """Remove synthetic/bad data — keep only records from 2025 onwards."""
    from datetime import date
    session = get_session()
    try:
        session.query(EUAPrice).filter(
            EUAPrice.date < date(2025, 1, 1)
        ).delete(synchronize_session=False)
        session.query(EUAPrice).filter(
            EUAPrice.source.like("%Synthetic%")
        ).delete(synchronize_session=False)
        session.commit()
        logger.info("Cleaned up old/synthetic records.")
    except Exception as e:
        session.rollback()
        logger.error(f"Cleanup failed: {e}")
    finally:
        session.close()


def purge_invalid_prices() -> int:
    """
    Delete records whose close price is outside the plausible EUA range (€30–€300).
    Returns the number of rows deleted.
    EUA has never traded below €30 since 2021, so anything outside this range
    indicates corrupt/wrong data (e.g. sequential row indices stored as prices).
    """
    session = get_session()
    try:
        deleted = session.query(EUAPrice).filter(
            (EUAPrice.close < 30.0) | (EUAPrice.close > 300.0)
        ).delete(synchronize_session=False)
        session.commit()
        if deleted:
            logger.warning(f"Purged {deleted} records with implausible prices (outside €30–€300).")
        return deleted
    except Exception as e:
        session.rollback()
        logger.error(f"Price purge failed: {e}")
        return 0
    finally:
        session.close()


def delete_all_prices() -> int:
    """
    Wipe the entire eua_prices table. Called before a forced re-fetch when
    data validity checks fail — necessary because upsert skips existing dates,
    so corrupt records for valid dates would never be overwritten otherwise.
    """
    session = get_session()
    try:
        deleted = session.query(EUAPrice).delete(synchronize_session=False)
        session.commit()
        logger.warning(f"Wiped all {deleted} price records for fresh re-fetch.")
        return deleted
    except Exception as e:
        session.rollback()
        logger.error(f"Full price wipe failed: {e}")
        return 0
    finally:
        session.close()


def is_price_data_valid() -> bool:
    """
    Return True if the stored price data looks like real EUA market data.
    Three checks:
      - At least 10 records exist
      - Latest record is within 14 calendar days (handles weekends/holidays)
      - Median price is in the €40–€110 range and max is below €130
        (EUA has never traded above ~€100 in 2025-2026; sequential/corrupt
        data like row-indices stored as prices routinely exceeds €130)
    """
    from datetime import date
    session = get_session()
    try:
        records = session.query(EUAPrice).order_by(EUAPrice.date.desc()).limit(90).all()
        if len(records) < 10:
            return False
        prices = sorted([r.close for r in records if r.close is not None])
        if not prices:
            return False
        min_price = prices[0]
        max_price = prices[-1]
        median = prices[len(prices) // 2]
        latest_date = records[0].date
        days_stale = (date.today() - latest_date).days
        price_ok = (40.0 <= min_price) and (median <= 110.0) and (max_price <= 130.0)
        return price_ok and (days_stale <= 14)
    except Exception as e:
        logger.error(f"Data validity check failed: {e}")
        return False
    finally:
        session.close()
